//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Impl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Angebotspositionen
    {
        public System.Guid ID { get; set; }
        public System.Guid AngebotID { get; set; }
        public string Freitext { get; set; }
        public Nullable<decimal> Reis { get; set; }
    
        public virtual Angebote Angebote { get; set; }
    }
}
