//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Impl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Angebote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Angebote()
        {
            this.Angebotspositionen = new HashSet<Angebotspositionen>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid KundeID { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual Kunden Kunden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Angebotspositionen> Angebotspositionen { get; set; }
    }
}
