//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Impl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rechnungspositionen
    {
        public int ID { get; set; }
        public int RechnungID { get; set; }
        public decimal Preis { get; set; }
        public string Freitext { get; set; }
    
        public virtual Rechnungen Rechnungen { get; set; }
    }
}
