//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Impl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rechnungen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rechnungen()
        {
            this.Rechnungspositionen = new HashSet<Rechnungspositionen>();
        }
    
        public int Rechnungsnummer { get; set; }
        public Nullable<System.DateTime> Erstellungsdatum { get; set; }
        public string Betreff { get; set; }
        public System.Guid KundeID { get; set; }
        public bool Bezahlt { get; set; }
    
        public virtual Kunden Kunden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rechnungspositionen> Rechnungspositionen { get; set; }
    }
}
